from tkinter import *
import tkinter as tk


def cadastro():

    _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
    _fgcolor = '#000000'  # X11 color: 'black'
    _compcolor = 'gray40' # X11 color: #666666
    _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
    _ana2color = 'beige' # X11 color: #f5f5dc
    _tabfg1 = 'black'
    _tabfg2 = 'black'
    _tabbg1 = 'grey75'
    _tabbg2 = 'grey89'
    _bgmode = 'light'

    class Tela_cadastro():
        def __init__(self, top=None):

            top = tk.Tk()
            top.geometry("600x450+348+126")
            top.minsize(120, 1)
            top.maxsize(3290, 1061)
            top.resizable(1,  1)
            top.title("Bem vindo!")
            top.configure(background="#dbf3fd")
            top.configure(highlightbackground="#d9d9d9")
            top.configure(highlightcolor="black")

            self.top = top
            self.selectedButton = tk.IntVar()
            teste = 0

            self.pessoa_fisica = tk.Radiobutton(self.top)
            self.pessoa_fisica.place(relx=0.083, rely=0.089, relheight=0.056, relwidth=0.213)
            self.pessoa_fisica.configure(activebackground="beige")
            self.pessoa_fisica.configure(activeforeground="black")
            self.pessoa_fisica.configure(anchor='w')
            self.pessoa_fisica.configure(background="#dbf3fd")
            self.pessoa_fisica.configure(compound='left')
            self.pessoa_fisica.configure(disabledforeground="#a3a3a3")
            self.pessoa_fisica.configure(font="-family {SimSun} -size 12")
            self.pessoa_fisica.configure(foreground="#000000")
            self.pessoa_fisica.configure(highlightbackground="#d9d9d9")
            self.pessoa_fisica.configure(highlightcolor="black")
            self.pessoa_fisica.configure(justify='left')
            self.pessoa_fisica.configure(selectcolor="#d9d9d9")
            self.pessoa_fisica.configure(text='''Pessoa fisica''')
            self.pessoa_fisica.configure(variable=self.selectedButton)
            self.pessoa_fisica.configure(value=1)

            self.pessoa_juridica = tk.Radiobutton(self.top)
            self.pessoa_juridica.place(relx=0.417, rely=0.089, relheight=0.056, relwidth=0.247)
            self.pessoa_juridica.configure(activebackground="beige")
            self.pessoa_juridica.configure(activeforeground="black")
            self.pessoa_juridica.configure(anchor='w')
            self.pessoa_juridica.configure(background="#dbf3fd")
            self.pessoa_juridica.configure(compound='left')
            self.pessoa_juridica.configure(disabledforeground="#a3a3a3")
            self.pessoa_juridica.configure(font="-family {SimSun} -size 12")
            self.pessoa_juridica.configure(foreground="#000000")
            self.pessoa_juridica.configure(highlightbackground="#d9d9d9")
            self.pessoa_juridica.configure(highlightcolor="black")
            self.pessoa_juridica.configure(justify='left')
            self.pessoa_juridica.configure(selectcolor="#d9d9d9")
            self.pessoa_juridica.configure(text='''Pessoa juridica''')
            self.pessoa_juridica.configure(variable=self.selectedButton)
            self.pessoa_juridica.configure(value=2)

            self.Label_nome = tk.Label(self.top)
            self.Label_nome.place(relx=0.067, rely=0.156, height=21, width=44)
            self.Label_nome.configure(activebackground="#f9f9f9")
            self.Label_nome.configure(anchor='w')
            self.Label_nome.configure(background="#dbf3fd")
            self.Label_nome.configure(compound='left')
            self.Label_nome.configure(disabledforeground="#a3a3a3")
            self.Label_nome.configure(font="-family {SimSun} -size 12")
            self.Label_nome.configure(foreground="#000000")
            self.Label_nome.configure(highlightbackground="#d9d9d9")
            self.Label_nome.configure(highlightcolor="black")
            self.Label_nome.configure(text='''Nome:''')

            self.Label_cpf = tk.Label(self.top)
            self.Label_cpf.place(relx=0.067, rely=0.222, height=21, width=44)
            self.Label_cpf.configure(activebackground="#f9f9f9")
            self.Label_cpf.configure(anchor='w')
            self.Label_cpf.configure(background="#dbf3fd")
            self.Label_cpf.configure(compound='left')
            self.Label_cpf.configure(disabledforeground="#a3a3a3")
            self.Label_cpf.configure(font="-family {SimSun} -size 12")
            self.Label_cpf.configure(foreground="#000000")
            self.Label_cpf.configure(highlightbackground="#d9d9d9")
            self.Label_cpf.configure(highlightcolor="black")
            self.Label_cpf.configure(text='''CPF:''')

            self.Label_nascimento = tk.Label(self.top)
            self.Label_nascimento.place(relx=0.067, rely=0.289, height=21, width=94)
            self.Label_nascimento.configure(activebackground="#f9f9f9")
            self.Label_nascimento.configure(anchor='w')
            self.Label_nascimento.configure(background="#dbf3fd")
            self.Label_nascimento.configure(compound='left')
            self.Label_nascimento.configure(disabledforeground="#a3a3a3")
            self.Label_nascimento.configure(font="-family {SimSun} -size 12")
            self.Label_nascimento.configure(foreground="#000000")
            self.Label_nascimento.configure(highlightbackground="#d9d9d9")
            self.Label_nascimento.configure(highlightcolor="black")
            self.Label_nascimento.configure(text='''Nascimento:''')

            self.Label_telefone = tk.Label(self.top)
            self.Label_telefone.place(relx=0.067, rely=0.356, height=21, width=84)
            self.Label_telefone.configure(activebackground="#f9f9f9")
            self.Label_telefone.configure(anchor='w')
            self.Label_telefone.configure(background="#dbf3fd")
            self.Label_telefone.configure(compound='left')
            self.Label_telefone.configure(disabledforeground="#a3a3a3")
            self.Label_telefone.configure(font="-family {SimSun} -size 12")
            self.Label_telefone.configure(foreground="#000000")
            self.Label_telefone.configure(highlightbackground="#d9d9d9")
            self.Label_telefone.configure(highlightcolor="black")
            self.Label_telefone.configure(text='''Telefone:''')

            self.Label_email = tk.Label(self.top)
            self.Label_email.place(relx=0.067, rely=0.422, height=21, width=64)
            self.Label_email.configure(activebackground="#f9f9f9")
            self.Label_email.configure(anchor='w')
            self.Label_email.configure(background="#dbf3fd")
            self.Label_email.configure(compound='left')
            self.Label_email.configure(disabledforeground="#a3a3a3")
            self.Label_email.configure(font="-family {SimSun} -size 12")
            self.Label_email.configure(foreground="#000000")
            self.Label_email.configure(highlightbackground="#d9d9d9")
            self.Label_email.configure(highlightcolor="black")
            self.Label_email.configure(text='''E-mail:''')

            self.Label_cep = tk.Label(self.top)
            self.Label_cep.place(relx=0.067, rely=0.489, height=21, width=44)
            self.Label_cep.configure(activebackground="#f9f9f9")
            self.Label_cep.configure(anchor='w')
            self.Label_cep.configure(background="#dbf3fd")
            self.Label_cep.configure(compound='left')
            self.Label_cep.configure(disabledforeground="#a3a3a3")
            self.Label_cep.configure(font="-family {SimSun} -size 12")
            self.Label_cep.configure(foreground="#000000")
            self.Label_cep.configure(highlightbackground="#d9d9d9")
            self.Label_cep.configure(highlightcolor="black")
            self.Label_cep.configure(text='''CEP:''')

            self.Label_cnpj = tk.Label(self.top)
            self.Label_cnpj.place(relx=0.533, rely=0.244, height=21, width=64)
            self.Label_cnpj.configure(activebackground="#f9f9f9")
            self.Label_cnpj.configure(anchor='w')
            self.Label_cnpj.configure(background="#dbf3fd")
            self.Label_cnpj.configure(compound='left')
            self.Label_cnpj.configure(disabledforeground="#a3a3a3")
            self.Label_cnpj.configure(font="-family {SimSun} -size 12")
            self.Label_cnpj.configure(foreground="#000000")
            self.Label_cnpj.configure(highlightbackground="#d9d9d9")
            self.Label_cnpj.configure(highlightcolor="black")
            self.Label_cnpj.configure(text='''CNPJ:''')

            self.Label_incricao = tk.Label(self.top)
            self.Label_incricao.place(relx=0.533, rely=0.311, height=21, width=104)
            self.Label_incricao.configure(activebackground="#f9f9f9")
            self.Label_incricao.configure(anchor='w')
            self.Label_incricao.configure(background="#dbf3fd")
            self.Label_incricao.configure(compound='left')
            self.Label_incricao.configure(disabledforeground="#a3a3a3")
            self.Label_incricao.configure(font="-family {SimSun} -size 12")
            self.Label_incricao.configure(foreground="#000000")
            self.Label_incricao.configure(highlightbackground="#d9d9d9")
            self.Label_incricao.configure(highlightcolor="black")
            self.Label_incricao.configure(text='''Ins.Estadual:''')

            self.entry_nome = tk.Entry(self.top)
            self.entry_nome.place(relx=0.15, rely=0.156, height=20, relwidth=0.54)
            self.entry_nome.configure(background="white")
            self.entry_nome.configure(disabledforeground="#a3a3a3")
            self.entry_nome.configure(font="TkFixedFont")
            self.entry_nome.configure(foreground="#000000")
            self.entry_nome.configure(highlightbackground="#d9d9d9")
            self.entry_nome.configure(highlightcolor="black")
            self.entry_nome.configure(insertbackground="black")
            self.entry_nome.configure(selectbackground="#c4c4c4")
            self.entry_nome.configure(selectforeground="black")

            self.entry_cpf = tk.Entry(self.top)
            self.entry_cpf.place(relx=0.133, rely=0.222, height=20, relwidth=0.29)
            self.entry_cpf.configure(background="white")
            self.entry_cpf.configure(disabledforeground="#a3a3a3")
            self.entry_cpf.configure(font="TkFixedFont")
            self.entry_cpf.configure(foreground="#000000")
            self.entry_cpf.configure(highlightbackground="#d9d9d9")
            self.entry_cpf.configure(highlightcolor="black")
            self.entry_cpf.configure(insertbackground="black")
            self.entry_cpf.configure(selectbackground="#c4c4c4")
            self.entry_cpf.configure(selectforeground="black")

            self.entry_nascimento = tk.Entry(self.top)
            self.entry_nascimento.place(relx=0.233, rely=0.289, height=20, relwidth=0.173)
            self.entry_nascimento.configure(background="white")
            self.entry_nascimento.configure(disabledforeground="#a3a3a3")
            self.entry_nascimento.configure(font="TkFixedFont")
            self.entry_nascimento.configure(foreground="#000000")
            self.entry_nascimento.configure(highlightbackground="#d9d9d9")
            self.entry_nascimento.configure(highlightcolor="black")
            self.entry_nascimento.configure(insertbackground="black")
            self.entry_nascimento.configure(selectbackground="#c4c4c4")
            self.entry_nascimento.configure(selectforeground="black")

            self.entry_telefone = tk.Entry(self.top)
            self.entry_telefone.place(relx=0.2, rely=0.356, height=20, relwidth=0.207)
            self.entry_telefone.configure(background="white")
            self.entry_telefone.configure(disabledforeground="#a3a3a3")
            self.entry_telefone.configure(font="TkFixedFont")
            self.entry_telefone.configure(foreground="#000000")
            self.entry_telefone.configure(highlightbackground="#d9d9d9")
            self.entry_telefone.configure(highlightcolor="black")
            self.entry_telefone.configure(insertbackground="black")
            self.entry_telefone.configure(selectbackground="#c4c4c4")
            self.entry_telefone.configure(selectforeground="black")

            self.entry_inscricao = tk.Entry(self.top)
            self.entry_inscricao.place(relx=0.717, rely=0.311, height=20, relwidth=0.19)
            self.entry_inscricao.configure(background="white")
            self.entry_inscricao.configure(disabledforeground="#a3a3a3")
            self.entry_inscricao.configure(font="TkFixedFont")
            self.entry_inscricao.configure(foreground="#000000")
            self.entry_inscricao.configure(highlightbackground="#d9d9d9")
            self.entry_inscricao.configure(highlightcolor="black")
            self.entry_inscricao.configure(insertbackground="black")
            self.entry_inscricao.configure(selectbackground="#c4c4c4")
            self.entry_inscricao.configure(selectforeground="black")

            self.entry_cnpj = tk.Entry(self.top)
            self.entry_cnpj.place(relx=0.617, rely=0.244, height=20, relwidth=0.29)
            self.entry_cnpj.configure(background="white")
            self.entry_cnpj.configure(disabledforeground="#a3a3a3")
            self.entry_cnpj.configure(font="TkFixedFont")
            self.entry_cnpj.configure(foreground="#000000")
            self.entry_cnpj.configure(highlightbackground="#d9d9d9")
            self.entry_cnpj.configure(highlightcolor="black")
            self.entry_cnpj.configure(insertbackground="black")
            self.entry_cnpj.configure(selectbackground="#c4c4c4")
            self.entry_cnpj.configure(selectforeground="black")

            self.entry_email = tk.Entry(self.top)
            self.entry_email.place(relx=0.183, rely=0.422, height=20, relwidth=0.307)
            self.entry_email.configure(background="white")
            self.entry_email.configure(disabledforeground="#a3a3a3")
            self.entry_email.configure(font="TkFixedFont")
            self.entry_email.configure(foreground="#000000")
            self.entry_email.configure(highlightbackground="#d9d9d9")
            self.entry_email.configure(highlightcolor="black")
            self.entry_email.configure(insertbackground="black")
            self.entry_email.configure(selectbackground="#c4c4c4")
            self.entry_email.configure(selectforeground="black")

            self.entry_cep = tk.Entry(self.top)
            self.entry_cep.place(relx=0.133, rely=0.489, height=20, relwidth=0.157)
            self.entry_cep.configure(background="white")
            self.entry_cep.configure(disabledforeground="#a3a3a3")
            self.entry_cep.configure(font="TkFixedFont")
            self.entry_cep.configure(foreground="#000000")
            self.entry_cep.configure(highlightbackground="#d9d9d9")
            self.entry_cep.configure(highlightcolor="black")
            self.entry_cep.configure(insertbackground="black")
            self.entry_cep.configure(selectbackground="#c4c4c4")
            self.entry_cep.configure(selectforeground="black")

            self.consulta_cadastro = tk.Button(self.top)
            self.consulta_cadastro.place(relx=0.067, rely=0.622, height=54, width=237)
            self.consulta_cadastro.configure(activebackground="beige")
            self.consulta_cadastro.configure(activeforeground="black")
            self.consulta_cadastro.configure(background="#ebfdfe")
            self.consulta_cadastro.configure(compound='left')
            self.consulta_cadastro.configure(disabledforeground="#a3a3a3")
            self.consulta_cadastro.configure(font="-family {SimSun} -size 10")
            self.consulta_cadastro.configure(foreground="#000000")
            self.consulta_cadastro.configure(highlightbackground="#d9d9d9")
            self.consulta_cadastro.configure(highlightcolor="black")
            self.consulta_cadastro.configure(pady="0")
            self.consulta_cadastro.configure(text='''Quero consultar um cadastro''')

            self.cadastrar = tk.Button(self.top)
            self.cadastrar.place(relx=0.617, rely=0.444, height=34, width=137)
            self.cadastrar.configure(activebackground="beige")
            self.cadastrar.configure(activeforeground="black")
            self.cadastrar.configure(background="#ebfdfe")
            self.cadastrar.configure(compound='left')
            self.cadastrar.configure(disabledforeground="#a3a3a3")
            self.cadastrar.configure(font="-family {SimSun} -size 10")
            self.cadastrar.configure(foreground="#000000")
            self.cadastrar.configure(highlightbackground="#d9d9d9")
            self.cadastrar.configure(highlightcolor="black")
            self.cadastrar.configure(pady="0")
            self.cadastrar.configure(text='''Cadastrar''')

            self.novo_cadastro = tk.Button(self.top)
            self.novo_cadastro.place(relx=0.533, rely=0.622, height=54, width=237)
            self.novo_cadastro.configure(activebackground="beige")
            self.novo_cadastro.configure(activeforeground="black")
            self.novo_cadastro.configure(background="#ebfdfe")
            self.novo_cadastro.configure(compound='left')
            self.novo_cadastro.configure(disabledforeground="#a3a3a3")
            self.novo_cadastro.configure(font="-family {SimSun} -size 10")
            self.novo_cadastro.configure(foreground="#000000")
            self.novo_cadastro.configure(highlightbackground="#d9d9d9")
            self.novo_cadastro.configure(highlightcolor="black")
            self.novo_cadastro.configure(pady="0")
            self.novo_cadastro.configure(text='''Novo Cadastro''')


            top.mainloop()

    Tela_cadastro()
