from tkinter import *
import tkinter as tk

def tela_consulta():

    _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
    _fgcolor = '#000000'  # X11 color: 'black'
    _compcolor = 'gray40'  # X11 color: #666666
    _ana1color = '#c3c3c3'  # Closest X11 color: 'gray76'
    _ana2color = 'beige'  # X11 color: #f5f5dc
    _tabfg1 = 'black'
    _tabfg2 = 'black'
    _tabbg1 = 'grey75'
    _tabbg2 = 'grey89'
    _bgmode = 'light'


    class Tela_consulta_cliente:
        def __init__(self, top=None):
            top = tk.Tk()
            top.geometry("600x450+348+126")
            top.minsize(120, 1)
            top.maxsize(3290, 1061)
            top.resizable(1, 1)
            top.title("Consulta clientes")
            top.configure(background="#dbf3fd")
            top.configure(highlightbackground="#d9d9d9")
            top.configure(highlightcolor="black")
            self.top = top

            self.Label1 = tk.Label(self.top)
            self.Label1.place(relx=0.067, rely=0.156, height=21, width=44)
            self.Label1.configure(activebackground="#f9f9f9")
            self.Label1.configure(anchor='w')
            self.Label1.configure(background="#dbf3fd")
            self.Label1.configure(compound='left')
            self.Label1.configure(disabledforeground="#a3a3a3")
            self.Label1.configure(font="-family {SimSun} -size 12")
            self.Label1.configure(foreground="#000000")
            self.Label1.configure(highlightbackground="#d9d9d9")
            self.Label1.configure(highlightcolor="black")
            self.Label1.configure(text='''Nome:''')

            self.Label1_1 = tk.Label(self.top)
            self.Label1_1.place(relx=0.067, rely=0.222, height=21, width=44)
            self.Label1_1.configure(activebackground="#f9f9f9")
            self.Label1_1.configure(anchor='w')
            self.Label1_1.configure(background="#dbf3fd")
            self.Label1_1.configure(compound='left')
            self.Label1_1.configure(disabledforeground="#a3a3a3")
            self.Label1_1.configure(font="-family {SimSun} -size 12")
            self.Label1_1.configure(foreground="#000000")
            self.Label1_1.configure(highlightbackground="#d9d9d9")
            self.Label1_1.configure(highlightcolor="black")
            self.Label1_1.configure(text='''CPF:''')

            self.Label1_1_1 = tk.Label(self.top)
            self.Label1_1_1.place(relx=0.067, rely=0.289, height=21, width=94)
            self.Label1_1_1.configure(activebackground="#f9f9f9")
            self.Label1_1_1.configure(anchor='w')
            self.Label1_1_1.configure(background="#dbf3fd")
            self.Label1_1_1.configure(compound='left')
            self.Label1_1_1.configure(disabledforeground="#a3a3a3")
            self.Label1_1_1.configure(font="-family {SimSun} -size 12")
            self.Label1_1_1.configure(foreground="#000000")
            self.Label1_1_1.configure(highlightbackground="#d9d9d9")
            self.Label1_1_1.configure(highlightcolor="black")
            self.Label1_1_1.configure(text='''Nascimento:''')

            self.Label1_1_1_1 = tk.Label(self.top)
            self.Label1_1_1_1.place(relx=0.067, rely=0.356, height=21, width=84)
            self.Label1_1_1_1.configure(activebackground="#f9f9f9")
            self.Label1_1_1_1.configure(anchor='w')
            self.Label1_1_1_1.configure(background="#dbf3fd")
            self.Label1_1_1_1.configure(compound='left')
            self.Label1_1_1_1.configure(disabledforeground="#a3a3a3")
            self.Label1_1_1_1.configure(font="-family {SimSun} -size 12")
            self.Label1_1_1_1.configure(foreground="#000000")
            self.Label1_1_1_1.configure(highlightbackground="#d9d9d9")
            self.Label1_1_1_1.configure(highlightcolor="black")
            self.Label1_1_1_1.configure(text='''Telefone:''')

            self.Label1_1_1_1_1 = tk.Label(self.top)
            self.Label1_1_1_1_1.place(relx=0.067, rely=0.422, height=21, width=64)
            self.Label1_1_1_1_1.configure(activebackground="#f9f9f9")
            self.Label1_1_1_1_1.configure(anchor='w')
            self.Label1_1_1_1_1.configure(background="#dbf3fd")
            self.Label1_1_1_1_1.configure(compound='left')
            self.Label1_1_1_1_1.configure(disabledforeground="#a3a3a3")
            self.Label1_1_1_1_1.configure(font="-family {SimSun} -size 12")
            self.Label1_1_1_1_1.configure(foreground="#000000")
            self.Label1_1_1_1_1.configure(highlightbackground="#d9d9d9")
            self.Label1_1_1_1_1.configure(highlightcolor="black")
            self.Label1_1_1_1_1.configure(text='''E-mail:''')

            self.Label1_1_2 = tk.Label(self.top)
            self.Label1_1_2.place(relx=0.067, rely=0.489, height=21, width=44)
            self.Label1_1_2.configure(activebackground="#f9f9f9")
            self.Label1_1_2.configure(anchor='w')
            self.Label1_1_2.configure(background="#dbf3fd")
            self.Label1_1_2.configure(compound='left')
            self.Label1_1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_1_2.configure(font="-family {SimSun} -size 12")
            self.Label1_1_2.configure(foreground="#000000")
            self.Label1_1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_1_2.configure(highlightcolor="black")
            self.Label1_1_2.configure(text='''CEP:''')

            self.Label1_1_1_1_1_1 = tk.Label(self.top)
            self.Label1_1_1_1_1_1.place(relx=0.533, rely=0.244, height=21, width=44)
            self.Label1_1_1_1_1_1.configure(activebackground="#f9f9f9")
            self.Label1_1_1_1_1_1.configure(anchor='w')
            self.Label1_1_1_1_1_1.configure(background="#dbf3fd")
            self.Label1_1_1_1_1_1.configure(compound='left')
            self.Label1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
            self.Label1_1_1_1_1_1.configure(font="-family {SimSun} -size 12")
            self.Label1_1_1_1_1_1.configure(foreground="#000000")
            self.Label1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
            self.Label1_1_1_1_1_1.configure(highlightcolor="black")
            self.Label1_1_1_1_1_1.configure(text='''CNPJ:''')

            self.Label1_1_1_2 = tk.Label(self.top)
            self.Label1_1_1_2.place(relx=0.533, rely=0.311, height=21, width=104)
            self.Label1_1_1_2.configure(activebackground="#f9f9f9")
            self.Label1_1_1_2.configure(anchor='w')
            self.Label1_1_1_2.configure(background="#dbf3fd")
            self.Label1_1_1_2.configure(compound='left')
            self.Label1_1_1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_1_1_2.configure(font="-family {SimSun} -size 12")
            self.Label1_1_1_2.configure(foreground="#000000")
            self.Label1_1_1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_1_1_2.configure(highlightcolor="black")
            self.Label1_1_1_2.configure(text='''Ins.Estadual:''')

            self.Button1 = tk.Button(self.top)
            self.Button1.place(relx=0.067, rely=0.622, height=54, width=237)
            self.Button1.configure(activebackground="beige")
            self.Button1.configure(activeforeground="black")
            self.Button1.configure(background="#ebfdfe")
            self.Button1.configure(compound='left')
            self.Button1.configure(disabledforeground="#a3a3a3")
            self.Button1.configure(font="-family {SimSun} -size 10")
            self.Button1.configure(foreground="#000000")
            self.Button1.configure(highlightbackground="#d9d9d9")
            self.Button1.configure(highlightcolor="black")
            self.Button1.configure(pady="0")
            self.Button1.configure(text='''Nova consulta''')

            self.Button1_2 = tk.Button(self.top)
            self.Button1_2.place(relx=0.533, rely=0.622, height=54, width=237)
            self.Button1_2.configure(activebackground="beige")
            self.Button1_2.configure(activeforeground="black")
            self.Button1_2.configure(background="#ebfdfe")
            self.Button1_2.configure(compound='left')
            self.Button1_2.configure(disabledforeground="#a3a3a3")
            self.Button1_2.configure(font="-family {SimSun} -size 10")
            self.Button1_2.configure(foreground="#000000")
            self.Button1_2.configure(highlightbackground="#d9d9d9")
            self.Button1_2.configure(highlightcolor="black")
            self.Button1_2.configure(pady="0")
            self.Button1_2.configure(text='''Retornar para cadastro''')

            self.Button2 = tk.Button(self.top)
            self.Button2.place(relx=0.517, rely=0.067, height=24, width=147)
            self.Button2.configure(activebackground="beige")
            self.Button2.configure(activeforeground="black")
            self.Button2.configure(background="#ebfdfe")
            self.Button2.configure(compound='left')
            self.Button2.configure(disabledforeground="#a3a3a3")
            self.Button2.configure(font="-family {SimSun} -size 9")
            self.Button2.configure(foreground="#000000")
            self.Button2.configure(highlightbackground="#d9d9d9")
            self.Button2.configure(highlightcolor="black")
            self.Button2.configure(pady="0")
            self.Button2.configure(text='''Consulta''')

            self.Label1_1_3 = tk.Label(self.top)
            self.Label1_1_3.place(relx=0.067, rely=0.067, height=21, width=174)
            self.Label1_1_3.configure(activebackground="#f9f9f9")
            self.Label1_1_3.configure(anchor='w')
            self.Label1_1_3.configure(background="#dbf3fd")
            self.Label1_1_3.configure(compound='left')
            self.Label1_1_3.configure(disabledforeground="#a3a3a3")
            self.Label1_1_3.configure(font="-family {SimSun} -size 12")
            self.Label1_1_3.configure(foreground="#000000")
            self.Label1_1_3.configure(highlightbackground="#d9d9d9")
            self.Label1_1_3.configure(highlightcolor="black")
            self.Label1_1_3.configure(text='''CPF/CNPJ:''')

            self.Entry2_1 = tk.Entry(self.top)
            self.Entry2_1.place(relx=0.2, rely=0.067, height=20, relwidth=0.29)
            self.Entry2_1.configure(background="white")
            self.Entry2_1.configure(disabledforeground="#a3a3a3")
            self.Entry2_1.configure(font="TkFixedFont")
            self.Entry2_1.configure(foreground="#000000")
            self.Entry2_1.configure(highlightbackground="#d9d9d9")
            self.Entry2_1.configure(highlightcolor="black")
            self.Entry2_1.configure(insertbackground="black")
            self.Entry2_1.configure(selectbackground="#c4c4c4")
            self.Entry2_1.configure(selectforeground="black")

            self.label_retorno_nome = tk.Label(self.top)
            self.label_retorno_nome.place(relx=0.15, rely=0.156, height=21, width =264)
            self.label_retorno_nome.configure(activebackground="#f9f9f9")
            self.label_retorno_nome.configure(anchor='w')
            self.label_retorno_nome.configure(background="#FFFFFF")
            self.label_retorno_nome.configure(compound='left')
            self.label_retorno_nome.configure(disabledforeground="#a3a3a3")
            self.label_retorno_nome.configure(foreground="#000000")
            self.label_retorno_nome.configure(highlightbackground="#d9d9d9")
            self.label_retorno_nome.configure(highlightcolor="black")
            self.label_retorno_nome.configure(relief="sunken")

            self.label_retorno_cpf = tk.Label(self.top)
            self.label_retorno_cpf.place(relx=0.133, rely=0.222, height=21, width =174)
            self.label_retorno_cpf.configure(activebackground="#f9f9f9")
            self.label_retorno_cpf.configure(anchor='w')
            self.label_retorno_cpf.configure(background="#FFFFFF")
            self.label_retorno_cpf.configure(compound='left')
            self.label_retorno_cpf.configure(disabledforeground="#a3a3a3")
            self.label_retorno_cpf.configure(foreground="#000000")
            self.label_retorno_cpf.configure(highlightbackground="#d9d9d9")
            self.label_retorno_cpf.configure(highlightcolor="black")
            self.label_retorno_cpf.configure(relief="sunken")

            self.label_retorno_nascimento = tk.Label(self.top)
            self.label_retorno_nascimento.place(relx=0.233, rely=0.289, height=21, width = 134)
            self.label_retorno_nascimento.configure(activebackground="#f9f9f9")
            self.label_retorno_nascimento.configure(anchor='w')
            self.label_retorno_nascimento.configure(background="#FFFFFF")
            self.label_retorno_nascimento.configure(compound='left')
            self.label_retorno_nascimento.configure(disabledforeground="#a3a3a3")
            self.label_retorno_nascimento.configure(foreground="#000000")
            self.label_retorno_nascimento.configure(highlightbackground="#d9d9d9")
            self.label_retorno_nascimento.configure(highlightcolor="black")
            self.label_retorno_nascimento.configure(relief="sunken")

            self.label_retorno_telefone = tk.Label(self.top)
            self.label_retorno_telefone.place(relx=0.2, rely=0.356, height=21, width = 144)
            self.label_retorno_telefone.configure(activebackground="#f9f9f9")
            self.label_retorno_telefone.configure(anchor='w')
            self.label_retorno_telefone.configure(background="#FFFFFF")
            self.label_retorno_telefone.configure(compound='left')
            self.label_retorno_telefone.configure(disabledforeground="#a3a3a3")
            self.label_retorno_telefone.configure(foreground="#000000")
            self.label_retorno_telefone.configure(highlightbackground="#d9d9d9")
            self.label_retorno_telefone.configure(highlightcolor="black")
            self.label_retorno_telefone.configure(relief="sunken")

            self.label_retorno_email = tk.Label(self.top)
            self.label_retorno_email.place(relx=0.167, rely=0.422, height=21, width = 214)
            self.label_retorno_email.configure(activebackground="#f9f9f9")
            self.label_retorno_email.configure(anchor='w')
            self.label_retorno_email.configure(background="#FFFFFF")
            self.label_retorno_email.configure(compound='left')
            self.label_retorno_email.configure(disabledforeground="#a3a3a3")
            self.label_retorno_email.configure(foreground="#000000")
            self.label_retorno_email.configure(highlightbackground="#d9d9d9")
            self.label_retorno_email.configure(highlightcolor="black")
            self.label_retorno_email.configure(relief="sunken")

            self.label_retorno_cep = tk.Label(self.top)
            self.label_retorno_cep.place(relx=0.133, rely=0.489, height=21, width = 134)
            self.label_retorno_cep.configure(activebackground="#f9f9f9")
            self.label_retorno_cep.configure(anchor='w')
            self.label_retorno_cep.configure(background="#FFFFFF")
            self.label_retorno_cep.configure(compound='left')
            self.label_retorno_cep.configure(disabledforeground="#a3a3a3")
            self.label_retorno_cep.configure(foreground="#000000")
            self.label_retorno_cep.configure(highlightbackground="#d9d9d9")
            self.label_retorno_cep.configure(highlightcolor="black")
            self.label_retorno_cep.configure(relief="sunken")

            self.label_retorno_cnpj = tk.Label(self.top)
            self.label_retorno_cnpj.place(relx=0.617, rely=0.244, height=21, width = 194)
            self.label_retorno_cnpj.configure(activebackground="#f9f9f9")
            self.label_retorno_cnpj.configure(anchor='w')
            self.label_retorno_cnpj.configure(background="#FFFFFF")
            self.label_retorno_cnpj.configure(compound='left')
            self.label_retorno_cnpj.configure(disabledforeground="#a3a3a3")
            self.label_retorno_cnpj.configure(foreground="#000000")
            self.label_retorno_cnpj.configure(highlightbackground="#d9d9d9")
            self.label_retorno_cnpj.configure(highlightcolor="black")
            self.label_retorno_cnpj.configure(relief="sunken")

            self.label_retorno_inscricao = tk.Label(self.top)
            self.label_retorno_inscricao.place(relx=0.717, rely=0.311, height=21, width = 154)
            self.label_retorno_inscricao.configure(activebackground="#f9f9f9")
            self.label_retorno_inscricao.configure(anchor='w')
            self.label_retorno_inscricao.configure(background="#FFFFFF")
            self.label_retorno_inscricao.configure(compound='left')
            self.label_retorno_inscricao.configure(disabledforeground="#a3a3a3")
            self.label_retorno_inscricao.configure(foreground="#000000")
            self.label_retorno_inscricao.configure(highlightbackground="#d9d9d9")
            self.label_retorno_inscricao.configure(highlightcolor="black")
            self.label_retorno_inscricao.configure(relief="sunken")

            top.mainloop()


    Tela_consulta_cliente()
